substitutions:
  device_name: "Toshiba ESTIA R32 Example"

esphome:
  name: toshiba-estia-example
  platform: ESP8266
  board: esp12e

logger:
  level: DEBUG

external_components:
  - source: ./components

status_led:
  pin:
    number: GPIO2
    inverted: true

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  parity: EVEN

climate:
  - platform: tu2c_link
    name: "${device_name}"
    id: toshiba_hp
    connected:
      name: ""${device_name} Connected"
    failed_crcs:
      name: "${device_name} Failed CRCs"
    vent:
      name: "${device_name} Vent Switch"
    on_data_received:
    - lambda: |-
        ESP_LOGD("TU2C", "Data received: %d bytes", x.size());